name: SpiritNotes
options:
  bundleIdPrefix: com.pleymob
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm
    from: "5.0.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"

targets:
  SpiritNotes:
    type: application
    platform: iOS
    sources:
      - path: SpiritNotes
    settings:
      base:
        INFOPLIST_FILE: SpiritNotes/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.pleymob.spiritnotes
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: H83F573KQB
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: SpiritNotes/App/SpiritNotes.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    dependencies:
      - package: Supabase
      - package: RevenueCat
        product: RevenueCat
      - package: GoogleSignIn

  SpiritNotesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SpiritNotesTests
    dependencies:
      - target: SpiritNotes
