name: SpiritNotes
options:
  bundleIdPrefix: com.pleymob
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm
    from: "5.0.0"

targets:
  SpiritNotes:
    type: application
    platform: iOS
    sources:
      - path: SpiritNotes
    settings:
      base:
        INFOPLIST_FILE: SpiritNotes/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.pleymob.spiritnotes
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Supabase
      - package: RevenueCat
        product: RevenueCat

  SpiritNotesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SpiritNotesTests
    dependencies:
      - target: SpiritNotes
